# Generated by Django 4.2.1 on 2023-05-25 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=50)),
                ('like_count', models.IntegerField()),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.CharField(choices=[('Mo', 'Moder'), ('Ad', 'Administrator'), ('Cr', 'Creator'), ('Cu', 'Customer')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SponsorTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='lifeHealther.myuser')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='lifeHealther.myuser')),
                ('info', models.TextField()),
                ('is_validated', models.BooleanField(default=False)),
                ('payment_details', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='lifeHealther.myuser')),
                ('payment_details', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='lifeHealther.myuser')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SponsorTierContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifeHealther.content')),
                ('sponsor_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifeHealther.sponsortier')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('like_count', models.IntegerField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifeHealther.content')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifeHealther.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifeHealther.creator')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifeHealther.customer')),
            ],
        ),
        migrations.AddField(
            model_name='sponsortier',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifeHealther.creator'),
        ),
        migrations.CreateModel(
            name='SponsorSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifeHealther.sponsortier')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifeHealther.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ContentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifeHealther.content')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifeHealther.customer')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifeHealther.creator'),
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifeHealther.comment')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifeHealther.customer')),
            ],
        ),
    ]
