"""
URL configuration for health_care_backend project.
"""
from django.contrib import admin
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from lifeHealther.views import (
    api_create_user_view,
    api_get_user_view,
    api_update_user_view,
    api_delete_user_view,
    api_create_creator_view,
    api_create_my_user_view,
    api_get_my_user_view,
    api_update_my_user_view,
    api_delete_my_user_view,
    api_get_creator_view,
    api_update_creator_view,
    api_delete_creator_view,
    api_create_customer_view,
    api_get_customer_view,
    api_update_customer_view,
    api_delete_customer_view,
    api_create_administrator_view,
    api_get_administrator_view,
    api_update_administrator_view,
    api_delete_administrator_view,
    api_create_moderator_view,
    api_get_moderator_view,
    api_update_moderator_view,
    api_delete_moderator_view,
    api_create_content_view,
    api_get_content_view,
    api_update_content_view,
    api_delete_content_view,
    api_create_comment_view,
    api_get_comment_view,
    api_update_comment_view,
    api_delete_comment_view,
    api_create_comment_like_view,
    api_get_comment_like_view,
    api_update_comment_like_view,
    api_delete_comment_like_view,
    api_create_content_like_view,
    api_get_content_like_view,
    api_update_content_like_view,
    api_delete_content_like_view,
    api_create_sponsor_tier_view,
    api_get_sponsor_tier_view,
    api_update_sponsor_tier_view,
    api_delete_sponsor_tier_view,
    api_create_sponsor_tier_content_view,
    api_get_sponsor_tier_content_view,
    api_update_sponsor_tier_content_view,
    api_delete_sponsor_tier_content_view,
    api_create_sponsor_subscription_view,
    api_get_sponsor_subscription_view,
    api_update_sponsor_subscription_view,
    api_delete_sponsor_subscription_view,
    api_create_subscription_view,
    api_get_subscription_view,
    api_update_subscription_view,
    api_delete_subscription_view,
    api_create_test_mongo_view,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/create', api_create_user_view),
    path('user/<int:user_id>', api_get_user_view),
    path('user/<int:user_id>/delete', api_delete_user_view),
    path('user/<int:user_id>/update', api_update_user_view),
    path('creator/create', api_create_creator_view),
    path('creator/<int:user_id>', api_get_creator_view),
    path('creator/<int:user_id>/delete', api_delete_creator_view),
    path('creator/<int:user_id>/update', api_update_creator_view),
    path('my_user/create', api_create_my_user_view),
    path('my_user/<int:my_user_id>', api_get_my_user_view),
    path('my_user/<int:my_user_id>/delete', api_delete_my_user_view),
    path('my_user/<int:my_user_id>/update', api_update_my_user_view),
    path('administrator/create', api_create_administrator_view),
    path('administrator/<int:user_id>', api_get_administrator_view),
    path('administrator/<int:user_id>/delete', api_delete_administrator_view),
    path('administrator/<int:user_id>/update', api_update_administrator_view),
    path('moderator/create', api_create_moderator_view),
    path('moderator/<int:user_id>', api_get_moderator_view),
    path('moderator/<int:user_id>/delete', api_delete_moderator_view),
    path('moderator/<int:user_id>/update', api_update_moderator_view),
    path('customer/create', api_create_customer_view),
    path('customer/<int:user_id>', api_get_customer_view),
    path('customer/<int:user_id>/delete', api_delete_customer_view),
    path('customer/<int:user_id>/update', api_update_customer_view),
    path('content/create', api_create_content_view),
    path('content/<int:user_id>', api_get_content_view),
    path('content/<int:user_id>/delete', api_delete_content_view),
    path('content/<int:user_id>/update', api_update_content_view),
    path('comment/create', api_create_comment_view),
    path('comment/<int:user_id>', api_get_comment_view),
    path('comment/<int:user_id>/delete', api_delete_comment_view),
    path('comment/<int:user_id>/update', api_update_comment_view),
    path('comment_like/create', api_create_comment_like_view),
    path('comment_like/<int:user_id>', api_get_comment_like_view),
    path('comment_like/<int:user_id>/delete', api_delete_comment_like_view),
    path('comment_like/<int:user_id>/update', api_update_comment_like_view),
    path('content_like/create', api_create_content_like_view),
    path('content_like/<int:user_id>', api_get_content_like_view),
    path('content_like/<int:user_id>/delete', api_delete_content_like_view),
    path('content_like/<int:user_id>/update', api_update_content_like_view),
    path('sponsor_tier/create', api_create_sponsor_tier_view),
    path('sponsor_tier/<int:user_id>', api_get_sponsor_tier_view),
    path('sponsor_tier/<int:user_id>/delete', api_delete_sponsor_tier_view),
    path('sponsor_tier/<int:user_id>/update', api_update_sponsor_tier_view),
    path('sponsor_tier_content/create', api_create_sponsor_tier_content_view),
    path('sponsor_tier_content/<int:user_id>', api_get_sponsor_tier_content_view),
    path('sponsor_tier_content/<int:user_id>/delete', api_delete_sponsor_tier_content_view),
    path('sponsor_tier_content/<int:user_id>/update', api_update_sponsor_tier_content_view),
    path('sponsor_subscription/create', api_create_sponsor_subscription_view),
    path('sponsor_subscription/<int:user_id>', api_get_sponsor_subscription_view),
    path('sponsor_subscription/<int:user_id>/delete', api_delete_sponsor_subscription_view),
    path('sponsor_subscription/<int:user_id>/update', api_update_sponsor_subscription_view),
    path('subscription/create', api_create_subscription_view),
    path('subscription/<int:user_id>', api_get_subscription_view),
    path('subscription/<int:user_id>/delete', api_delete_subscription_view),
    path('subscription/<int:user_id>/update', api_update_subscription_view),
    path('test_mongo',api_create_test_mongo_view),
]

urlpatterns += staticfiles_urlpatterns()
